apiVersion: v1
kind: Namespace
metadata:
  name: avi-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ako
  namespace: avi-system
spec:
  interval: 5m
  url: https://projects.registry.vmware.com/chartrepo/ako
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ako
  namespace: avi-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ako
      version: ">=1.5.0"
      sourceRef:
        kind: HelmRepository
        name: ako
        namespace: avi-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: ako-values
